name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: securedatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo_mysql, zip, dom
        coverage: none

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h127.0.0.1 -uroot -proot --silent; then
            break
          fi
          sleep 2
        done

    - name: Debug repository structure
      run: |
        echo "Current directory:"
        pwd
        echo "\nListing all files recursively:"
        find . -type f
        echo "\nSecureVersion directory contents:"
        ls -la SecureVersion/

    - name: Create database schema
      run: |
        echo "Creating database schema..."
        mysql -h127.0.0.1 -uroot -proot << EOF
        CREATE DATABASE IF NOT EXISTS securedatabase;
        USE securedatabase;

        CREATE TABLE IF NOT EXISTS users (
            id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
            username VARCHAR(50) NOT NULL UNIQUE,
            fullname VARCHAR(100) NOT NULL,
            email VARCHAR(100) NOT NULL UNIQUE,
            dob DATE NOT NULL,
            password VARCHAR(255) NOT NULL,
            phone VARCHAR(20) NOT NULL,
            address TEXT NOT NULL,
            is_admin TINYINT(1) NOT NULL DEFAULT 0,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        );
        EOF

    - name: Check PHP syntax errors
      run: |
        cd SecureVersion
        find . -type f -name '*.php' -print0 | xargs -0 -n1 php -l

    - name: Run login system tests
      run: |
        echo "Current directory:"
        pwd
        echo "\nChanging to SecureVersion directory..."
        cd SecureVersion
        echo "\nCurrent directory after cd:"
        pwd
        echo "\nListing files in current directory:"
        ls -la
        echo "\nRunning tests..."
        php ci_test.php
