name: Secure version-  Vulnerability Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secure_security_test:
    name: Secure Security Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: securedatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, zip, dom
          coverage: none
      - name: Create database schema
        run: |
          echo "Creating database schema..."
          mysql -h127.0.0.1 -uroot -proot << EOF
          DROP TABLE IF EXISTS users;
          CREATE DATABASE IF NOT EXISTS securedatabase;
          USE securedatabase;
          CREATE TABLE IF NOT EXISTS users (
              id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
              username VARCHAR(50) NOT NULL UNIQUE,
              fullname VARCHAR(100) NOT NULL,
              email VARCHAR(100) NOT NULL UNIQUE,
              dob DATE NOT NULL,
              password VARCHAR(255) NOT NULL,
              phone VARCHAR(20) NOT NULL,
              address TEXT NOT NULL,
              is_admin TINYINT(1) NOT NULL DEFAULT 0,
              created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
              CHECK (username <> ''),
              CHECK (fullname <> ''),
              CHECK (email REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'),
              CHECK (dob <= CURDATE()),
              CHECK (CHAR_LENGTH(password) >= 8),
              CHECK (phone REGEXP '^[0-9\\-\\+]{9,15}$'),
              CHECK (address <> '')
          );
          EOF
      - name: Run secure vulnerability scan
        run: |
          cd SecureVersion/tests
          php secure_vulnerability_scan.php