name:  A new scan for the Unsecure version- added null value vulnerability, phone number validation vulnerability and dob validation vulnerability, password complexity vulnerability

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unsecure_security_test:
    name: Unsecure version- Security Test
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: unsecuredatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, zip, dom
          coverage: none
      - name: Create database schema
        run: |
          echo "Creating database schema..."
          mysql -h127.0.0.1 -uroot -proot << EOF
          CREATE DATABASE IF NOT EXISTS unsecuredatabase;
          USE unsecuredatabase;
          CREATE TABLE IF NOT EXISTS users (
              id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
              username VARCHAR(50) NOT NULL UNIQUE,
              fullname VARCHAR(100) NOT NULL,
              email VARCHAR(100) NOT NULL UNIQUE,
              dob DATE NOT NULL,
              password VARCHAR(255) NOT NULL,
              phone VARCHAR(20) NOT NULL,
              address TEXT NOT NULL,
              is_admin TINYINT(1) NOT NULL DEFAULT 0,
              created_at DATETIME DEFAULT CURRENT_TIMESTAMP
          );
          EOF
      - name: Run unsecure vulnerability scan
        run: |
          cd UnsecureVersion/tests
          php vulnerability_scan.php 